---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-toolbox
  namespace: default
  labels:
    app: alpine-toolbox
spec:
  automountServiceAccountToken: false
  containers:
    - name: alpine-toolbox
      image: ghcr.io/containeroo/alpine-toolbox:latest
      imagePullPolicy: IfNotPresent
      command:
        - bash
      args:
        - -c
        - "sleep infinity"
      resources: {}
