name: Publish container image

on:
  push:
    tags:
      - v*

jobs:
  multi-arch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare release tag
        id: tag
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/containeroo/alpine-toolbox:latest
            ghcr.io/containeroo/alpine-toolbox:${{ steps.tag.outputs.version }}
