---
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update datasource in Dockerfile
        run: |
          sed \
            --regexp-extended \
            --quiet \
            's/.*alpine:([0-9]).([0-9]+).*/\1 \2/p' Dockerfile | \
          xargs \
            --max-args=2 \
            bash \
            -c \
              'sed \
                --in-place \
                --regexp-extended \
                "s/alpine_[0-9]_[0-9]+/alpine_${0}_${1}/" Dockerfile'
      - name: Update component versions in README.md
        run: |
          sed \
            --regexp-extended \
            --quiet \
            's/(ARG|ENV)\s*(.*)_VERSION(=|\s*)(.*)/\L\2 (\4)/p' Dockerfile | \
          xargs \
            --max-args=2 \
            bash \
            -c \
              'sed \
                --in-place \
                --regexp-extended \
                "s/${0}.*$/${0} ${1}/" README.md'
      - name: Update alpine version in README.md
        run: |
          sed \
            --regexp-extended \
            --quiet \
            's/FROM\s+alpine:(.*)/(\1)/p' Dockerfile | \
          xargs \
            bash \
            -c \
              'sed \
                --in-place \
                --regexp-extended \
                "s/linux (.*) with/linux ${0} with/" README.md'
      - name: Commit & push updated README.md
        run: |
          git config --local user.name  ${{ github.actor }}
          if ! git diff-index --quiet HEAD; then
            git add README.md
            git commit -m "README: update version"
            git push https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
          fi
      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/changelog-configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          ignorePreReleases: "${{ !contains(github.ref, '-rc') }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          prerelease: "${{ contains(github.ref, '-rc') }}"
          # Ensure target branch for release is "master"
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/containeroo/alpine-toolbox:latest
            ghcr.io/containeroo/alpine-toolbox:${{ steps.tag.outputs.version }}
