---
on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update README.md
        run: |
          sed \
            --regexp-extended \
            --quiet \
            's/(ARG|ENV)\s*(.*)_VERSION(=|\s*)(.*)/\L\2 (\4)/p' Dockerfile | \
            xargs \
              --max-args=2 \
              bash -c
                'sed \
                  --in-place \
                  --regexp-extended \
                  "s/${0}/${0} ${1}/" README.md'
      - name: Commit updated README.md
        run: |
          git add README.md
          git commit -m "README: update version"
          git push -u origin master
