name: update README.md

on:
  workflow_call:

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Determine default branch
        id: def
        run: echo "branch=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v5
        with:
          ref: ${{ steps.def.outputs.branch }}
          fetch-depth: 0

      - name: Update datasource in Dockerfile
        run: |
          sed -r -n 's/.*alpine:([0-9])\.([0-9]+).*/\1 \2/p' Dockerfile | \
          xargs -n2 bash -lc \
            'sed -i -r "s/alpine_[0-9]_[0-9]+/alpine_${0}_${1}/" Dockerfile'

      - name: Update component versions in README.md
        shell: bash
        run: |
          mapfile -t lines < <(sed -rn 's/^(ARG|ENV)[[:space:]]+([A-Z0-9_]+)_VERSION(=|[[:space:]])(.*)$/\L\2 \4/p' Dockerfile | tr '_' '-')
          for l in "${lines[@]}"; do
            name="${l% *}"
            ver="${l#* }"
            # Update lines like "- bash (...)" regardless of current version
            sed -i -r "s#(^- *${name})( .*|\$)#\1 (${ver})#" README.md
          done

      - name: Update alpine version in README.md
        run: |
          ver=$(sed -rn 's/^FROM[[:space:]]+alpine:(.*)$/\1/p' Dockerfile)
          [ -n "$ver" ] && sed -i -r "s#(alpine linux )\([^)]*\)( with)#\1(${ver})\2#i" README.md

      - name: Push updated README.md
        uses: EndBug/add-and-commit@v9
        with:
          message: "README: update version"
          default_author: github_actions
          add: "README.md"
          branch: ${{ steps.def.outputs.branch }}
